## Anna Giczewska ST544 - Project 2
Date 3/27/2026  

This project has two main parts. In Part I, I create and test a custom PySpark class called SparkDataCheck that helps check and summarize data quality in Spark SQL style DataFrames. In Part II, I analyze NFL quarterback data using both pandas-on-Spark and Spark SQL DataFrames.

Throughout the notebook, I include code, output, and short explanations to describe what I am doing and why each step is included.

## Part I - Creating and Testing the SparkDataCheck Class

In this part of the project, I work with a Spark SQL style DataFrame and create a custom Python class that wraps the DataFrame and provides methods for checking data quality and summarizing the data.

The class is stored in a separate .py file, and I import it into this notebook so I can test each method here.

In [6]:
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

#start Spark Session for this project
spark = SparkSession.builder.appName("Project2").getOrCreate()
#turn off ANSI mode to avoid certainstrict Spark errors
spark.conf.set("spark.sql.ansi.enabled", "false")

In [2]:
#import importlib so I can reload my Python file after edditing it
import importlib
#import my claddfile
import spark_data_check
#reload the file so the notebook uses the newest version
importlib.reload(spark_data_check)

#Import the SparkDataCheck class from my file
from spark_data_check import SparkDataCheck

# Show which file is being imported
print(spark_data_check.__file__)

# Check which methods exist on the class itself
print(hasattr(SparkDataCheck, "from_csv"))
print(hasattr(SparkDataCheck, "from_pandas"))
print(hasattr(SparkDataCheck, "check_numeric_range"))
print(hasattr(SparkDataCheck, "check_string_levels"))
print(hasattr(SparkDataCheck, "check_missing"))
print(hasattr(SparkDataCheck, "summarize_numeric_min_max"))
print(hasattr(SparkDataCheck, "count_string_levels"))

/home/jupyter-agiczew@ncsu.edu/st554_project2/spark_data_check.py
True
True
True
True
True
True
True

In [3]:
air_url = "https://www4.stat.ncsu.edu/online/datasets/air.csv"
#read the CSV from the website into a pandas DataFrame
air_download = pd.read_csv(air_url)
#save a local copy of air.csv file in my project folder
air_download.to_csv("air.csv", index=False)

# Check the first few rows and column names
print(air_download.columns.tolist())
air_download.head()

['Unnamed: 0', 'Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH']

,Unnamed: 0,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888

In [4]:
#createa SparkData Object by reading CSV with Spark
air_check = SparkDataCheck.from_csv(spark, "air.csv")
#confirm object creation
type(air_check)

spark_data_check.SparkDataCheck

In [5]:
#show data
air_check.df.show(5)
air_check.df.printSchema()

+----------+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|Unnamed: 0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+----------+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|         0|3/10/2004|2026-03-27 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|         1|3/10/2004|2026-03-27 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|         2|3/10/2004|2026-03-27 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|         3|3/10/2004|2026-03-27 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|         4|3/10/2004|2026-03-27 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+----------+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows
root
 |-- Unnamed: 0: integer (nullable = true)
 |-- Date: string (nullable = true)
 |-- Time: timestamp (nullable = true)
 |-- CO(GT): double (nullable = true)
 |-- PT08.S1(CO): integer (nullable = true)
 |-- NMHC(GT): integer (nullable = true)
 |-- C6H6(GT): double (nullable = true)
 |-- PT08.S2(NMHC): integer (nullable = true)
 |-- NOx(GT): integer (nullable = true)
 |-- PT08.S3(NOx): integer (nullable = true)
 |-- NO2(GT): integer (nullable = true)
 |-- PT08.S4(NO2): integer (nullable = true)
 |-- PT08.S5(O3): integer (nullable = true)
 |-- T: double (nullable = true)
 |-- RH: double (nullable = true)
 |-- AH: double (nullable = true)

In [6]:
#read CSV into pandas DataFrame
air_pd = pd.read_csv("air.csv")
#Create a SparkDataCheck object from the pandas DataFrame
air_check_pd = SparkDataCheck.from_pandas(spark, air_pd)
#confirm object was created
type(air_check_pd)

spark_data_check.SparkDataCheck

In [7]:
air_check_pd.df.show(5)

+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

In [8]:
# Create helper columns for testing the validation methods
air_check.df = (
    air_check.df
    .withColumn(
        "time_period",
        F.when(F.col("Time") < "12:00:00", "morning")
         .when(F.col("Time") < "18:00:00", "afternoon")
         .otherwise("evening")
    )
    .withColumn(
        "temp_group",
        F.when(F.col("T").isNull(), F.lit(None))
         .when(F.col("T") < 10, "cold")
         .when(F.col("T") < 20, "mild")
         .otherwise("warm")
    )
    .withColumn(
        "co_clean",
        F.when(F.col("CO(GT)") == -200, F.lit(None))
         .otherwise(F.col("CO(GT)"))
    )
)

# Show the new helper columns
air_check.df.select("Time", "T", "CO(GT)", "time_period", "temp_group", "co_clean").show(10)

+-------------------+----+------+-----------+----------+--------+
|               Time|   T|CO(GT)|time_period|temp_group|co_clean|
+-------------------+----+------+-----------+----------+--------+
|2026-03-27 18:00:00|13.6|   2.6|    evening|      mild|     2.6|
|2026-03-27 19:00:00|13.3|   2.0|    evening|      mild|     2.0|
|2026-03-27 20:00:00|11.9|   2.2|    evening|      mild|     2.2|
|2026-03-27 21:00:00|11.0|   2.2|    evening|      mild|     2.2|
|2026-03-27 22:00:00|11.2|   1.6|    evening|      mild|     1.6|
|2026-03-27 23:00:00|11.2|   1.2|    evening|      mild|     1.2|
|2026-03-27 00:00:00|11.3|   1.2|    morning|      mild|     1.2|
|2026-03-27 01:00:00|10.7|   1.0|    morning|      mild|     1.0|
|2026-03-27 02:00:00|10.7|   0.9|    morning|      mild|     0.9|
|2026-03-27 03:00:00|10.3|   0.6|    morning|      mild|     0.6|
+-------------------+----+------+-----------+----------+--------+
only showing top 10 rows

**Method 1: Check check_numeric_range()**

In [24]:
# Check whether temperature is in a reasonable range
air_check.check_numeric_range("T", lower=0, upper=40, new_col_name="temp_ok")
air_check.df.select("T", "temp_ok").show(10)

+----+-------+
|   T|temp_ok|
+----+-------+
|13.6|   true|
|13.3|   true|
|11.9|   true|
|11.0|   true|
|11.2|   true|
|11.2|   true|
|11.3|   true|
|10.7|   true|
|10.7|   true|
|10.3|   true|
+----+-------+
only showing top 10 rows

In [25]:
# Check whether relative humidity is at most 100
air_check.check_numeric_range("RH", upper=100, new_col_name="rh_ok")
air_check.df.select("RH", "rh_ok").show(10)

+----+-----+
|  RH|rh_ok|
+----+-----+
|48.9| true|
|47.7| true|
|54.0| true|
|60.0| true|
|59.6| true|
|59.2| true|
|56.8| true|
|60.0| true|
|59.7| true|
|60.2| true|
+----+-----+
only showing top 10 rows

In [26]:
# Test a bad input using a string column
air_check.check_numeric_range("time_period", lower=1, upper=10)

Column 'time_period' is not numeric.

In [27]:
# Check whether AH is at least 0.5
air_check.check_numeric_range("AH", lower=0.5, new_col_name="AH_ge_0_5")
air_check.df.select("AH", "AH_ge_0_5").show(10)

+------+---------+
|    AH|AH_ge_0_5|
+------+---------+
|0.7578|     true|
|0.7255|     true|
|0.7502|     true|
|0.7867|     true|
|0.7888|     true|
|0.7848|     true|
|0.7603|     true|
|0.7702|     true|
|0.7648|     true|
|0.7517|     true|
+------+---------+
only showing top 10 rows

In [28]:
# Check whether co_clean is between 0 and 5
air_check.check_numeric_range("co_clean", lower=0, upper=5, new_col_name="co_clean_0_5")
air_check.df.select("co_clean", "co_clean_0_5").show(10)

+--------+------------+
|co_clean|co_clean_0_5|
+--------+------------+
|     2.6|        true|
|     2.0|        true|
|     2.2|        true|
|     2.2|        true|
|     1.6|        true|
|     1.2|        true|
|     1.2|        true|
|     1.0|        true|
|     0.9|        true|
|     0.6|        true|
+--------+------------+
only showing top 10 rows

**Method 2: Check check_string_levels()**

In [29]:
# Check whether time_period belongs to the expected levels
air_check.check_string_levels(
    "time_period",
    ["morning", "afternoon", "evening"],
    new_col_name="time_period_ok"
)
air_check.df.select("time_period", "time_period_ok").show(10)

+-----------+--------------+
|time_period|time_period_ok|
+-----------+--------------+
|    evening|          true|
|    evening|          true|
|    evening|          true|
|    evening|          true|
|    evening|          true|
|    evening|          true|
|    morning|          true|
|    morning|          true|
|    morning|          true|
|    morning|          true|
+-----------+--------------+
only showing top 10 rows

In [30]:
# Check whether temp_group belongs to the expected levels
air_check.check_string_levels(
    "temp_group",
    ["cold", "mild", "warm"],
    new_col_name="temp_group_ok"
)
air_check.df.select("temp_group", "temp_group_ok").show(10)

+----------+-------------+
|temp_group|temp_group_ok|
+----------+-------------+
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
|      mild|         true|
+----------+-------------+
only showing top 10 rows

In [31]:
# Test a bad input using a numeric column
air_check.check_string_levels("T", ["cold", "warm"])

Column 'T' is not a string column.

In [32]:
# Check stricter valid levels for time_period
air_check.check_string_levels(
    "time_period",
    ["morning", "afternoon"],
    new_col_name="time_period_day_only"
)
air_check.df.select("time_period", "time_period_day_only").show(10)

+-----------+--------------------+
|time_period|time_period_day_only|
+-----------+--------------------+
|    evening|               false|
|    evening|               false|
|    evening|               false|
|    evening|               false|
|    evening|               false|
|    evening|               false|
|    morning|                true|
|    morning|                true|
|    morning|                true|
|    morning|                true|
+-----------+--------------------+
only showing top 10 rows

In [33]:
# Check stricter valid levels for temp_group
air_check.check_string_levels(
    "temp_group",
    ["cold", "warm"],
    new_col_name="temp_group_cold_warm"
)
air_check.df.select("temp_group", "temp_group_cold_warm").show(10)

+----------+--------------------+
|temp_group|temp_group_cold_warm|
+----------+--------------------+
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
|      mild|               false|
+----------+--------------------+
only showing top 10 rows

**Method 3: check_missing()**

In [34]:
# Check missing values in the cleaned CO column
air_check.check_missing("co_clean", new_col_name="co_missing")
air_check.df.select("CO(GT)", "co_clean", "co_missing").show(15)

+------+--------+----------+
|CO(GT)|co_clean|co_missing|
+------+--------+----------+
|   2.6|     2.6|     false|
|   2.0|     2.0|     false|
|   2.2|     2.2|     false|
|   2.2|     2.2|     false|
|   1.6|     1.6|     false|
|   1.2|     1.2|     false|
|   1.2|     1.2|     false|
|   1.0|     1.0|     false|
|   0.9|     0.9|     false|
|   0.6|     0.6|     false|
|-200.0|    NULL|      true|
|   0.7|     0.7|     false|
|   0.7|     0.7|     false|
|   1.1|     1.1|     false|
|   2.0|     2.0|     false|
+------+--------+----------+
only showing top 15 rows

In [35]:
# Create another column with some artificial missing values for testing
air_check.df = air_check.df.withColumn(
    "ah_test",
    F.when(F.col("AH") < 0.5, F.lit(None)).otherwise(F.col("AH"))
)

# Check missing values in the new test column
air_check.check_missing("ah_test", new_col_name="ah_test_missing")
air_check.df.select("AH", "ah_test", "ah_test_missing").show(15)

+------+-------+---------------+
|    AH|ah_test|ah_test_missing|
+------+-------+---------------+
|0.7578| 0.7578|          false|
|0.7255| 0.7255|          false|
|0.7502| 0.7502|          false|
|0.7867| 0.7867|          false|
|0.7888| 0.7888|          false|
|0.7848| 0.7848|          false|
|0.7603| 0.7603|          false|
|0.7702| 0.7702|          false|
|0.7648| 0.7648|          false|
|0.7517| 0.7517|          false|
|0.7465| 0.7465|          false|
|0.7366| 0.7366|          false|
|0.7353| 0.7353|          false|
|0.7417| 0.7417|          false|
|0.7408| 0.7408|          false|
+------+-------+---------------+
only showing top 15 rows

In [36]:
# Check missingness in T
air_check.check_missing("T", new_col_name="T_missing")
air_check.df.select("T", "T_missing").show(10)

+----+---------+
|   T|T_missing|
+----+---------+
|13.6|    false|
|13.3|    false|
|11.9|    false|
|11.0|    false|
|11.2|    false|
|11.2|    false|
|11.3|    false|
|10.7|    false|
|10.7|    false|
|10.3|    false|
+----+---------+
only showing top 10 rows

In [37]:
# Check missingness in time_period
air_check.check_missing("time_period", new_col_name="time_period_missing")
air_check.df.select("time_period", "time_period_missing").show(10)

+-----------+-------------------+
|time_period|time_period_missing|
+-----------+-------------------+
|    evening|              false|
|    evening|              false|
|    evening|              false|
|    evening|              false|
|    evening|              false|
|    evening|              false|
|    morning|              false|
|    morning|              false|
|    morning|              false|
|    morning|              false|
+-----------+-------------------+
only showing top 10 rows

In [38]:
# Check missingness in temp_group
air_check.check_missing("temp_group", new_col_name="temp_group_missing")
air_check.df.select("temp_group", "temp_group_missing").show(10)

+----------+------------------+
|temp_group|temp_group_missing|
+----------+------------------+
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
|      mild|             false|
+----------+------------------+
only showing top 10 rows

**Method 4: Check summarize_numeric_min_max()**

In [12]:
# Summarize one numeric column without grouping
result1 = air_check.summarize_numeric_min_max("T")

# Check the output type
print(type(result1))

# Show the result
result1

<class 'pandas.core.frame.DataFrame'>

   T_min  T_max
0 -200.0   44.6

In [13]:
# Summarize one numeric column grouped by a string column
result2 = air_check.summarize_numeric_min_max("RH", group_by="time_period")

# Check the output type
print(type(result2))

# Show the result
result2

<class 'pandas.core.frame.DataFrame'>

  time_period  RH_min  RH_max
0   afternoon  -200.0    88.7
1     evening  -200.0    87.2
2     morning  -200.0    87.1

In [14]:
# Summarize all numeric columns without grouping
result3 = air_check.summarize_numeric_min_max()

# Check the output type
print(type(result3))

# Show the result
result3

26/03/27 22:11:45 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

<class 'pandas.core.frame.DataFrame'>

,Unnamed: 0_min,Unnamed: 0_max,CO(GT)_min,CO(GT)_max,PT08.S1(CO)_min,PT08.S1(CO)_max,NMHC(GT)_min,NMHC(GT)_max,C6H6(GT)_min,C6H6(GT)_max,...,T_min,T_max,RH_min,RH_max,AH_min,AH_max,co_clean_min,co_clean_max,ah_test_min,ah_test_max
0,0,9356,-200.0,11.9,-200,2040,-200,1189,-200.0,63.7,...,-200.0,44.6,-200.0,88.7,-200.0,2.231,0.1,11.9,0.5002,2.231

In [15]:
# Summarize all numeric columns grouped by a string column
result4 = air_check.summarize_numeric_min_max(group_by="time_period")

# Check the output type
print(type(result4))

# Show the result
result4

<class 'pandas.core.frame.DataFrame'>

,time_period,Unnamed: 0_min,Unnamed: 0_max,CO(GT)_min,CO(GT)_max,PT08.S1(CO)_min,PT08.S1(CO)_max,NMHC(GT)_min,NMHC(GT)_max,C6H6(GT)_min,...,T_min,T_max,RH_min,RH_max,AH_min,AH_max,co_clean_min,co_clean_max,ah_test_min,ah_test_max
0,afternoon,18,9356,-200.0,8.4,-200,1915,-200,832,-200.0,...,-200.0,44.6,-200.0,88.7,-200.0,2.2310,0.1,8.4,0.5002,2.2310
1,evening,0,9341,-200.0,11.9,-200,2040,-200,1189,-200.0,...,-200.0,40.6,-200.0,87.2,-200.0,2.1107,0.1,11.9,0.5007,2.1107
2,morning,6,9353,-200.0,8.1,-200,1961,-200,1129,-200.0,...,-200.0,38.3,-200.0,87.1,-200.0,2.1719,0.1,8.1,0.5007,2.1719

In [16]:
# Test a bad input using a string column
air_check.summarize_numeric_min_max("time_period")

Column 'time_period' is not numeric.

**Method 5: Check count_string_levels()**

In [17]:
# Count levels of one string column
result5 = air_check.count_string_levels("time_period")

# Check the output type
print(type(result5))

# Show the result
result5

<class 'pandas.core.frame.DataFrame'>

  time_period  count
0   afternoon   2337
1     evening   2340
2     morning   4680

In [18]:
# Count levels of another string column
result6 = air_check.count_string_levels("temp_group")

#show the results
result6

  temp_group  count
0       cold   2032
1       mild   3577
2       warm   3748

In [19]:
# Count combinations of two string columns
result7 = air_check.count_string_levels("time_period", "temp_group")

# Check the output type
print(type(result7))

# Show the result
result7

<class 'pandas.core.frame.DataFrame'>

  time_period temp_group  count
0   afternoon       cold    281
1   afternoon       mild    761
2   afternoon       warm   1295
3     evening       cold    484
4     evening       mild    884
5     evening       warm    972
6     morning       cold   1267
7     morning       mild   1932
8     morning       warm   1481

In [20]:
# Test a bad input using a numeric column
air_check.count_string_levels("T")

Column 'T' is numeric.

In [21]:
# Test a bad input where the second column is numeric
air_check.count_string_levels("time_period", "RH")

Column 'RH' is numeric.

**Example using object created from pandas**

In [39]:
# One example using the object created from a pandas DataFrame
result_pd = air_check_pd.summarize_numeric_min_max("T")

# Check the output type
print(type(result_pd))

# Show the result
result_pd

<class 'pandas.core.frame.DataFrame'>

   T_min  T_max
0 -200.0   44.6

## Part II - NFL Analysis

In this section, I analyze weekly NFL quarterback data using two Spark APIs: pandas-on-Spark and Spark SQL DataFrames. I use the same filtering and summary steps in both approaches so I can compare the results.

In [7]:
# Set this before importing pandas-on-Spark
import os
os.environ["PYARROW_IGNORE_TIMEZONE"] = "1"

# Import pandas-on-Spark
import pyspark.pandas as ps

**Part IIA: pandas-on-Spark**

In [9]:
# Read with an explicit index column to avoid the default-index warning
nfl_ps = ps.read_csv("weekly_nfl_data.csv", index_col="player_id")

# Show the first 5 rows
nfl_ps.head(5)

           player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
player_id
00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

In [10]:
# Show all column names
list(nfl_ps.columns)

['player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

In [11]:
# Keep only QB regular-season rows from 2005 to 2023
qb_ps = nfl_ps[
    (nfl_ps["position"] == "QB") &
    (nfl_ps["season_type"] == "REG") &
    (nfl_ps["season"] >= 2005) &
    (nfl_ps["season"] <= 2023)
][[
    "player_display_name",
    "season",
    "week",
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "interceptions"
]]

# Show first few filtered rows
qb_ps.head(5)

           player_display_name  season  week  completions  attempts  passing_yards  passing_tds  interceptions
player_id
00-0000722          Tony Banks    2005    17           14        25          173.0            1            2.0
00-0000865       Charlie Batch    2005     9            9        16           65.0            0            1.0
00-0000865       Charlie Batch    2005    10           13        19          150.0            0            0.0
00-0000865       Charlie Batch    2005    16            1         1           31.0            1            0.0
00-0001335          Jeff Blake    2005     2            1         1           11.0            0            0.0

In [12]:
# Group by player and season and compute sums and means
qb_summary_ps = qb_ps.groupby(["player_display_name", "season"]).agg({
    "week": ["sum", "mean"],
    "completions": ["sum", "mean"],
    "attempts": ["sum", "mean"],
    "passing_yards": ["sum", "mean"],
    "passing_tds": ["sum", "mean"],
    "interceptions": ["sum", "mean"]
}).reset_index()

# Flatten multi-level column names
new_cols = []
for col_name in qb_summary_ps.columns:
    if isinstance(col_name, tuple):
        left, right = col_name
        if right == "":
            new_cols.append(left)
        else:
            new_cols.append(f"{left}_{right}")
    else:
        new_cols.append(col_name)

qb_summary_ps.columns = new_cols

# Create the required variables
qb_summary_ps["completion_percentage"] = (
    qb_summary_ps["completions_sum"] / qb_summary_ps["attempts_sum"]
)

qb_summary_ps["td_int_ratio"] = (
    qb_summary_ps["passing_tds_sum"] / qb_summary_ps["interceptions_sum"]
)

# Show the first few rows
qb_summary_ps.head(5)

  player_display_name  season  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
0       Jake Delhomme    2006        99   7.615385              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154               0.610209      1.545455
1        Jake Plummer    2005       144   9.000000              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500               0.607456      2.571429
2         Matt Schaub    2006        60  12.000000               18          3.600000            27       5.400000              208.0           41.600000                1          0.200000                2.0            0.400000               0.666667      0.500000
3         Vince Young    2006       143   9.533333              184         12.266667           356      23.733333             2199.0          146.600000               12          0.800000               13.0            0.866667               0.516854      0.923077
4       Kerry Collins    2007        48   8.000000               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                0.0            0.000000               0.609756           NaN

In [13]:
# Keep only player-season rows with at least 50 attempts
qb_summary_ps_50 = qb_summary_ps[qb_summary_ps["attempts_sum"] >= 50]

# Show first few rows
qb_summary_ps_50.head(5)

  player_display_name  season  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
0       Jake Delhomme    2006        99   7.615385              263         20.230769           431      33.153846             2805.0          215.769231               17          1.307692               11.0            0.846154               0.610209      1.545455
1        Jake Plummer    2005       144   9.000000              277         17.312500           456      28.500000             3366.0          210.375000               18          1.125000                7.0            0.437500               0.607456      2.571429
3         Vince Young    2006       143   9.533333              184         12.266667           356      23.733333             2199.0          146.600000               12          0.800000               13.0            0.866667               0.516854      0.923077
4       Kerry Collins    2007        48   8.000000               50          8.333333            82      13.666667              531.0           88.500000                0          0.000000                0.0            0.000000               0.609756           NaN
6       Charlie Batch    2006        71  10.142857               30          4.285714            52       7.428571              477.0           68.142857                5          0.714286                0.0            0.000000               0.576923           inf

In [14]:
# Top 40 by completion percentage
qb_summary_ps_50.sort_values("completion_percentage", ascending=False).head(40)

     player_display_name  season  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
1409       C.J. Beathard    2023        65  10.833333               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
1248          Colt McCoy    2021        62   8.857143               74         10.571429            99      14.142857              740.0          105.714286                3          0.428571                1.0            0.142857               0.747475      3.000000
900          Matt Schaub    2019        52  10.400000               50         10.000000            67      13.400000              580.0          116.000000                3          0.600000                1.0            0.200000               0.746269      3.000000
953           Drew Brees    2018       130   8.666667              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1057          Drew Brees    2019       119  10.818182              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1338       Mason Rudolph    2023        66  16.500000               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1133         Taysom Hill    2020       147   9.187500               88          5.500000           121       7.562500              928.0           58.000000                4          0.250000                2.0            0.125000               0.727273      2.000000
1007          Nick Foles    2018        51  10.200000              141         28.200000           195      39.000000             1413.0          282.600000                7          1.400000                4.0            0.800000               0.723077      1.750000
917           Drew Brees    2017       148   9.250000              386         24.125000           536      33.500000             4334.0          270.875000               23          1.437500                8.0            0.500000               0.720149      2.875000
851         Sam Bradford    2016       146   9.733333              395         26.333333           552      36.800000             3877.0          258.466667               20          1.333333                5.0            0.333333               0.715580      4.000000
510           Drew Brees    2011       142   8.875000              471         29.437500           660      41.250000             5535.0          345.937500               46          2.875000               14.0            0.875000               0.713636      3.285714
838           Colt McCoy    2014        57  11.400000               91         18.200000           128      25.600000             1057.0          211.400000                4          0.800000                3.0            0.600000               0.710938      1.333333
1262       Aaron Rodgers    2020       148   9.250000              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1453        Bailey Zappe    2022        22   5.500000               65         16.250000            92      23.000000              781.0          195.250000                5          1.250000                3.0            0.750000               0.706522      1.666667
242           Drew Brees    2009       131   8.733333              363         24.200000           514      34.266667             4388.0          292.533333               34          2.266667               11.0            0.733333               0.706226      3.090909
1098          Drew Brees    2020        97   8.083333              275         22.916667           390      32.500000             2942.0          245.166667               24          2.000000                6.0            0.500000               0.705128      4.000000
1437          Joe Burrow    2021       143   8.937500              366         22.875000           520      32.500000             4611.0          288.187500               34          2.125000               14.0            0.875000               0.703846      2.428571
1101          Derek Carr    2019       147   9.187500              361         22.562500           513      32.062500             4054.0          253.375000               21          1.312500                8.0            0.500000               0.703704      2.625000
1303       Jake Browning    2023       117  13.000000              171         19.000000           243      27.000000             1936.0          215.111111               12          1.333333                7.0            0.777778               0.703704      1.714286
901         Chase Daniel    2019        20   6.666667               45         15.000000            64      21.333333              435.0          145.000000                3          1.000000                2.0            0.666667               0.703125      1.500000
1079      Ryan Tannehill    2019       128  10.666667              201         16.750000           286      23.833333             2742.0          228.500000               22          1.833333                6.0            0.500000               0.702797      3.666667
1088      Deshaun Watson    2020       145   9.062500              382         23.875000           544      34.000000             4823.0          301.437500               33          2.062500                7.0            0.437500               0.702206      4.714286
503           Alex Smith    2012        63   6.300000              153         15.300000           218      21.800000             1737.0          173.700000               13          1.300000                5.0            0.500000               0.701835      2.600000
942         Kirk Cousins    2018       143   8.937500              425         26.562500           606      37.875000             4298.0          268.625000               30          1.875000               10.0            0.625000               0.701320      3.000000
129         Jamie Martin    2005        92  11.500000              124         15.500000           177      22.125000             1277.0          159.625000                5          0.625000                7.0            0.875000               0.700565      0.714286
884           Drew Brees    2016       148   9.250000              471         29.437500           673      42.062500             5208.0          325.500000               37          2.312500               15.0            0.937500               0.699851      2.466667
770            Tony Romo    2014       133   8.866667              304         20.266667           435      29.000000             3705.0          247.000000               34          2.266667                9.0            0.600000               0.698851      3.777778
872            Matt Ryan    2016       142   8.875000              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
876         Kirk Cousins    2015       145   9.062500              379         23.687500           543      33.937500             4166.0          260.375000               29          1.812500               11.0            0.687500               0.697974      2.636364
1316          Geno Smith    2022       160   9.411765              399         23.470588           572      33.647059             4282.0          251.882353               30          1.764706               11.0            0.647059               0.697552      2.727273
926         Chase Daniel    2018        38   9.500000               53         13.250000            76      19.000000              515.0          128.750000                3          0.750000                2.0            0.500000               0.697368      1.500000
914         Carson Wentz    2018        93   8.454545              279         25.363636           401      36.454545             3074.0          279.454545               21          1.909091                7.0            0.636364               0.695761      3.000000
1397        Dak Prescott    2023       164   9.647059              410         24.117647           590      34.705882             4516.0          265.647059               36          2.117647                9.0            0.529412               0.694915      4.000000
553        Philip Rivers    2013       145   9.062500              378         23.625000           544      34.000000             4478.0          279.875000               32          2.000000               11.0            0.687500               0.694853      2.909091
362            Tony Romo    2010        24   4.000000              148         24.666667           213      35.500000             1605.0          267.500000               11          1.833333                7.0            1.166667               0.694836      1.571429
1295        Kirk Cousins    2023        36   4.500000              216         27.000000           311      38.875000             2331.0          291.375000               18          2.250000                5.0            0.625000               0.694534      3.600000
928            Matt Ryan    2018       145   9.062500              422         26.375000           608      38.000000             4924.0          307.750000               35          2.187500                7.0            0.437500               0.694079      5.000000
1433         Brock Purdy    2023       144   9.000000              308         19.250000           444      27.750000             4280.0          267.500000               31          1.937500               11.0            0.687500               0.693694      2.818182
41             Jim Sorgi    2005        57  11.400000               43          8.600000            62      12.400000              444.0           88.800000                3          0.600000                1.0            0.200000               0.693548      3.000000
772       Brandon Weeden    2015        45   7.500000               97         16.166667           140      23.333333             1043.0          173.833333                5          0.833333                2.0            0.333333               0.692857      2.500000

In [15]:
# Top 40 by TD to INT ratio
qb_summary_ps_50.sort_values("td_int_ratio", ascending=False).head(40)

     player_display_name  season  week_sum  week_mean  completions_sum  completions_mean  attempts_sum  attempts_mean  passing_yards_sum  passing_yards_mean  passing_tds_sum  passing_tds_mean  interceptions_sum  interceptions_mean  completion_percentage  td_int_ratio
6          Charlie Batch    2006        71  10.142857               30          4.285714            52       7.428571              477.0           68.142857                5          0.714286                0.0            0.000000               0.576923           inf
26           Matt Schaub    2005        65   9.285714               33          4.714286            64       9.142857              495.0           70.714286                4          0.571429                0.0            0.000000               0.515625           inf
73          Todd Collins    2007        62  15.500000               67         16.750000           105      26.250000              888.0          222.000000                5          1.250000                0.0            0.000000               0.638095           inf
455           Troy Smith    2007        62  15.500000               40         10.000000            76      19.000000              452.0          113.000000                2          0.500000                0.0            0.000000               0.526316           inf
520          Jake Locker    2011        51  10.200000               34          6.800000            66      13.200000              542.0          108.400000                4          0.800000                0.0            0.000000               0.515152           inf
775          Brian Hoyer    2016        27   4.500000              134         22.333333           200      33.333333             1445.0          240.833333                6          1.000000                0.0            0.000000               0.670000           inf
778           Nick Foles    2016        17   8.500000               36         18.000000            55      27.500000              410.0          205.000000                3          1.500000                0.0            0.000000               0.654545           inf
812       Derek Anderson    2014        30   6.000000               65         13.000000            97      19.400000              701.0          140.200000                5          1.000000                0.0            0.000000               0.670103           inf
940      Jimmy Garoppolo    2016        49   8.166667               43          7.166667            63      10.500000              502.0           83.666667                4          0.666667                0.0            0.000000               0.682540           inf
984           Matt Moore    2019        54   9.000000               59          9.833333            91      15.166667              659.0          109.833333                4          0.666667                0.0            0.000000               0.648352           inf
1127       C.J. Beathard    2020        67  11.166667               66         11.000000           104      17.333333              787.0          131.166667                6          1.000000                0.0            0.000000               0.634615           inf
1334         Andy Dalton    2023         8   4.000000               34         17.000000            58      29.000000              361.0          180.500000                2          1.000000                0.0            0.000000               0.586207           inf
1338       Mason Rudolph    2023        66  16.500000               55         13.750000            74      18.500000              719.0          179.750000                3          0.750000                0.0            0.000000               0.743243           inf
1365      Desmond Ridder    2022        66  16.500000               73         18.250000           115      28.750000              708.0          177.000000                2          0.500000                0.0            0.000000               0.634783           inf
1409       C.J. Beathard    2023        65  10.833333               40          6.666667            53       8.833333              349.0           58.166667                1          0.166667                0.0            0.000000               0.754717           inf
763            Tom Brady    2016       134  11.166667              291         24.250000           432      36.000000             3554.0          296.166667               28          2.333333                2.0            0.166667               0.673611     14.000000
639           Nick Foles    2013       129   9.923077              203         15.615385           317      24.384615             2891.0          222.384615               27          2.076923                2.0            0.153846               0.640379     13.500000
618          Josh McCown    2013        92  11.500000              149         18.625000           224      28.000000             1829.0          228.625000               13          1.625000                1.0            0.125000               0.665179     13.000000
989        Aaron Rodgers    2018       146   9.125000              372         23.250000           597      37.312500             4442.0          277.625000               25          1.562500                2.0            0.125000               0.623116     12.500000
200          Damon Huard    2006        69   6.900000              148         14.800000           244      24.400000             1878.0          187.800000               11          1.100000                1.0            0.100000               0.606557     11.000000
1262       Aaron Rodgers    2020       148   9.250000              372         23.250000           526      32.875000             4299.0          268.687500               48          3.000000                5.0            0.312500               0.707224      9.600000
1111       Aaron Rodgers    2021       149   9.312500              366         22.875000           531      33.187500             4115.0          257.187500               37          2.312500                4.0            0.250000               0.689266      9.250000
286            Tom Brady    2010       148   9.250000              324         20.250000           492      30.750000             3900.0          243.750000               36          2.250000                4.0            0.250000               0.658537      9.000000
20         Jake Delhomme    2007         6   2.000000               55         18.333333            86      28.666667              617.0          205.666667                8          2.666667                1.0            0.333333               0.639535      8.000000
695        Aaron Rodgers    2014       144   9.000000              341         21.312500           520      32.500000             4381.0          273.812500               38          2.375000                5.0            0.312500               0.655769      7.600000
662        Aaron Rodgers    2011       128   8.533333              342         22.800000           501      33.400000             4636.0          309.066667               45          3.000000                6.0            0.400000               0.682635      7.500000
1057          Drew Brees    2019       119  10.818182              281         25.545455           378      34.363636             2979.0          270.818182               27          2.454545                4.0            0.363636               0.743386      6.750000
1073       Aaron Rodgers    2019       142   8.875000              353         22.062500           569      35.562500             4002.0          250.125000               26          1.625000                4.0            0.250000               0.620387      6.500000
953           Drew Brees    2018       130   8.666667              364         24.266667           489      32.600000             3992.0          266.133333               32          2.133333                5.0            0.333333               0.744376      6.400000
1267     Patrick Mahomes    2020       126   8.400000              390         26.000000           588      39.200000             4740.0          316.000000               38          2.533333                6.0            0.400000               0.663265      6.333333
145            Tom Brady    2007       143   8.937500              398         24.875000           578      36.125000             4806.0          300.375000               50          3.125000                8.0            0.500000               0.688581      6.250000
951       Russell Wilson    2019       142   8.875000              341         21.312500           516      32.250000             4110.0          256.875000               31          1.937500                5.0            0.312500               0.660853      6.200000
23         David Garrard    2007       105   8.750000              208         17.333333           325      27.083333             2509.0          209.083333               18          1.500000                3.0            0.250000               0.640000      6.000000
418     Matthew Stafford    2010        26   6.500000               57         14.250000            96      24.000000              535.0          133.750000                6          1.500000                1.0            0.250000               0.593750      6.000000
1168       Lamar Jackson    2019       128   8.533333              265         17.666667           401      26.733333             3127.0          208.466667               36          2.400000                6.0            0.400000               0.660848      6.000000
1026        Dak Prescott    2016       146   9.125000              311         19.437500           459      28.687500             3667.0          229.187500               23          1.437500                4.0            0.250000               0.677560      5.750000
766        Aaron Rodgers    2016       149   9.312500              401         25.062500           610      38.125000             4428.0          276.750000               40          2.500000                7.0            0.437500               0.657377      5.714286
673       Peyton Manning    2013       144   9.000000              450         28.125000           659      41.187500             5477.0          342.312500               55          3.437500               10.0            0.625000               0.682853      5.500000
872            Matt Ryan    2016       142   8.875000              373         23.312500           534      33.375000             4944.0          309.000000               38          2.375000                7.0            0.437500               0.698502      5.428571
1038          Alex Smith    2017       126   8.400000              341         22.733333           505      33.666667             4042.0          269.466667               26          1.733333                5.0            0.333333               0.675248      5.200000

**Part IIB: Spark SQL DataFrame API**

In [16]:
# Read the weekly NFL data using Spark SQL
nfl_spark = spark.read.load(
    "weekly_nfl_data.csv",
    format="csv",
    sep=",",
    inferSchema=True,
    header=True
)

# Show the first 5 rows
nfl_spark.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

In [17]:
# Show all column names
nfl_spark.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

In [18]:
# Keep only QB regular-season rows from 2005 to 2023
qb_spark = (
    nfl_spark
    .filter(
        (F.col("position") == "QB") &
        (F.col("season_type") == "REG") &
        (F.col("season") >= 2005) &
        (F.col("season") <= 2023)
    )
    .select(
        "player_display_name",
        "season",
        "week",
        "completions",
        "attempts",
        "passing_yards",
        "passing_tds",
        "interceptions"
    )
)

# Show first few filtered rows
qb_spark.show(5)

+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|player_display_name|season|week|completions|attempts|passing_yards|passing_tds|interceptions|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
|         Tony Banks|  2005|  17|         14|      25|        173.0|          1|          2.0|
|      Charlie Batch|  2005|   9|          9|      16|         65.0|          0|          1.0|
|      Charlie Batch|  2005|  10|         13|      19|        150.0|          0|          0.0|
|      Charlie Batch|  2005|  16|          1|       1|         31.0|          1|          0.0|
|         Jeff Blake|  2005|   2|          1|       1|         11.0|          0|          0.0|
+-------------------+------+----+-----------+--------+-------------+-----------+-------------+
only showing top 5 rows

In [19]:
# Group by player and season and compute sums and means
qb_summary_spark = (
    qb_spark
    .groupBy("player_display_name", "season")
    .agg(
        F.sum("week").alias("week_sum"),
        F.mean("week").alias("week_mean"),
        F.sum("completions").alias("completions_sum"),
        F.mean("completions").alias("completions_mean"),
        F.sum("attempts").alias("attempts_sum"),
        F.mean("attempts").alias("attempts_mean"),
        F.sum("passing_yards").alias("passing_yards_sum"),
        F.mean("passing_yards").alias("passing_yards_mean"),
        F.sum("passing_tds").alias("passing_tds_sum"),
        F.mean("passing_tds").alias("passing_tds_mean"),
        F.sum("interceptions").alias("interceptions_sum"),
        F.mean("interceptions").alias("interceptions_mean")
    )
    .withColumn(
        "completion_percentage",
        F.col("completions_sum") / F.col("attempts_sum")
    )
    .withColumn(
        "td_int_ratio",
        F.col("passing_tds_sum") / F.col("interceptions_sum")
    )
)

# Show first few rows
qb_summary_spark.show(5)

+-------------------+------+--------+-----------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+------------------+---------------------+------------------+
|player_display_name|season|week_sum|        week_mean|completions_sum|  completions_mean|attempts_sum|     attempts_mean|passing_yards_sum|passing_yards_mean|passing_tds_sum|  passing_tds_mean|interceptions_sum|interceptions_mean|completion_percentage|      td_int_ratio|
+-------------------+------+--------+-----------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+------------------+---------------------+------------------+
|      Jake Delhomme|  2006|      99|7.615384615384615|            263| 20.23076923076923|         431| 33.15384615384615|           2805.0|215.76923076923077|             17|1.3076923076923077|             11.0|0.8461538461538461|   0.6102088167053364|1.5454545454545454|
|       Jake Plummer|  2005|     144|              9.0|            277|           17.3125|         456|              28.5|           3366.0|           210.375|             18|             1.125|              7.0|            0.4375|   0.6074561403508771|2.5714285714285716|
|        Matt Schaub|  2006|      60|             12.0|             18|               3.6|          27|               5.4|            208.0|              41.6|              1|               0.2|              2.0|               0.4|   0.6666666666666666|               0.5|
|        Vince Young|  2006|     143|9.533333333333333|            184|12.266666666666667|         356|23.733333333333334|           2199.0|             146.6|             12|               0.8|             13.0|0.8666666666666667|   0.5168539325842697|0.9230769230769231|
|      Kerry Collins|  2007|      48|              8.0|             50| 8.333333333333334|          82|13.666666666666666|            531.0|              88.5|              0|               0.0|              0.0|               0.0|   0.6097560975609756|              NULL|
+-------------------+------+--------+-----------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+------------------+---------------------+------------------+
only showing top 5 rows

In [20]:
# Keep only player-season rows with at least 50 attempts
qb_summary_spark_50 = qb_summary_spark.filter(F.col("attempts_sum") >= 50)

In [21]:
# Top 40 by completion percentage
qb_summary_spark_50.orderBy(F.col("completion_percentage").desc()).show(40, truncate=False)

+-------------------+------+--------+------------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+
|player_display_name|season|week_sum|week_mean         |completions_sum|completions_mean  |attempts_sum|attempts_mean     |passing_yards_sum|passing_yards_mean|passing_tds_sum|passing_tds_mean   |interceptions_sum|interceptions_mean |completion_percentage|td_int_ratio      |
+-------------------+------+--------+------------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+
|C.J. Beathard      |2023  |65      |10.833333333333334|40             |6.666666666666667 |53          |8.833333333333334 |349.0            |58.166666666666664|1              |0.16666666666666666|0.0              |0.0                |0.7547169811320755   |NULL              |
|Colt McCoy         |2021  |62      |8.857142857142858 |74             |10.571428571428571|99          |14.142857142857142|740.0            |105.71428571428571|3              |0.42857142857142855|1.0              |0.14285714285714285|0.7474747474747475   |3.0               |
|Matt Schaub        |2019  |52      |10.4              |50             |10.0              |67          |13.4              |580.0            |116.0             |3              |0.6                |1.0              |0.2                |0.746268656716418    |3.0               |
|Drew Brees         |2018  |130     |8.666666666666666 |364            |24.266666666666666|489         |32.6              |3992.0           |266.1333333333333 |32             |2.1333333333333333 |5.0              |0.3333333333333333 |0.7443762781186094   |6.4               |
|Drew Brees         |2019  |119     |10.818181818181818|281            |25.545454545454547|378         |34.36363636363637 |2979.0           |270.8181818181818 |27             |2.4545454545454546 |4.0              |0.36363636363636365|0.7433862433862434   |6.75              |
|Mason Rudolph      |2023  |66      |16.5              |55             |13.75             |74          |18.5              |719.0            |179.75            |3              |0.75               |0.0              |0.0                |0.7432432432432432   |NULL              |
|Taysom Hill        |2020  |147     |9.1875            |88             |5.5               |121         |7.5625            |928.0            |58.0              |4              |0.25               |2.0              |0.125              |0.7272727272727273   |2.0               |
|Nick Foles         |2018  |51      |10.2              |141            |28.2              |195         |39.0              |1413.0           |282.6             |7              |1.4                |4.0              |0.8                |0.7230769230769231   |1.75              |
|Drew Brees         |2017  |148     |9.25              |386            |24.125            |536         |33.5              |4334.0           |270.875           |23             |1.4375             |8.0              |0.5                |0.7201492537313433   |2.875             |
|Sam Bradford       |2016  |146     |9.733333333333333 |395            |26.333333333333332|552         |36.8              |3877.0           |258.46666666666664|20             |1.3333333333333333 |5.0              |0.3333333333333333 |0.7155797101449275   |4.0               |
|Drew Brees         |2011  |142     |8.875             |471            |29.4375           |660         |41.25             |5535.0           |345.9375          |46             |2.875              |14.0             |0.875              |0.7136363636363636   |3.2857142857142856|
|Colt McCoy         |2014  |57      |11.4              |91             |18.2              |128         |25.6              |1057.0           |211.4             |4              |0.8                |3.0              |0.6                |0.7109375            |1.3333333333333333|
|Aaron Rodgers      |2020  |148     |9.25              |372            |23.25             |526         |32.875            |4299.0           |268.6875          |48             |3.0                |5.0              |0.3125             |0.7072243346007605   |9.6               |
|Bailey Zappe       |2022  |22      |5.5               |65             |16.25             |92          |23.0              |781.0            |195.25            |5              |1.25               |3.0              |0.75               |0.7065217391304348   |1.6666666666666667|
|Drew Brees         |2009  |131     |8.733333333333333 |363            |24.2              |514         |34.266666666666666|4388.0           |292.53333333333336|34             |2.2666666666666666 |11.0             |0.7333333333333333 |0.7062256809338522   |3.090909090909091 |
|Drew Brees         |2020  |97      |8.083333333333334 |275            |22.916666666666668|390         |32.5              |2942.0           |245.16666666666666|24             |2.0                |6.0              |0.5                |0.7051282051282052   |4.0               |
|Joe Burrow         |2021  |143     |8.9375            |366            |22.875            |520         |32.5              |4611.0           |288.1875          |34             |2.125              |14.0             |0.875              |0.7038461538461539   |2.4285714285714284|
|Derek Carr         |2019  |147     |9.1875            |361            |22.5625           |513         |32.0625           |4054.0           |253.375           |21             |1.3125             |8.0              |0.5                |0.7037037037037037   |2.625             |
|Jake Browning      |2023  |117     |13.0              |171            |19.0              |243         |27.0              |1936.0           |215.11111111111111|12             |1.3333333333333333 |7.0              |0.7777777777777778 |0.7037037037037037   |1.7142857142857142|
|Chase Daniel       |2019  |20      |6.666666666666667 |45             |15.0              |64          |21.333333333333332|435.0            |145.0             |3              |1.0                |2.0              |0.6666666666666666 |0.703125             |1.5               |
|Ryan Tannehill     |2019  |128     |10.666666666666666|201            |16.75             |286         |23.833333333333332|2742.0           |228.5             |22             |1.8333333333333333 |6.0              |0.5                |0.7027972027972028   |3.6666666666666665|
|Deshaun Watson     |2020  |145     |9.0625            |382            |23.875            |544         |34.0              |4823.0           |301.4375          |33             |2.0625             |7.0              |0.4375             |0.7022058823529411   |4.714285714285714 |
|Alex Smith         |2012  |63      |6.3               |153            |15.3              |218         |21.8              |1737.0           |173.7             |13             |1.3                |5.0              |0.5                |0.7018348623853211   |2.6               |
|Kirk Cousins       |2018  |143     |8.9375            |425            |26.5625           |606         |37.875            |4298.0           |268.625           |30             |1.875              |10.0             |0.625              |0.7013201320132013   |3.0               |
|Jamie Martin       |2005  |92      |11.5              |124            |15.5              |177         |22.125            |1277.0           |159.625           |5              |0.625              |7.0              |0.875              |0.7005649717514124   |0.7142857142857143|
|Drew Brees         |2016  |148     |9.25              |471            |29.4375           |673         |42.0625           |5208.0           |325.5             |37             |2.3125             |15.0             |0.9375             |0.6998514115898959   |2.466666666666667 |
|Tony Romo          |2014  |133     |8.866666666666667 |304            |20.266666666666666|435         |29.0              |3705.0           |247.0             |34             |2.2666666666666666 |9.0              |0.6                |0.6988505747126437   |3.7777777777777777|
|Matt Ryan          |2016  |142     |8.875             |373            |23.3125           |534         |33.375            |4944.0           |309.0             |38             |2.375              |7.0              |0.4375             |0.6985018726591761   |5.428571428571429 |
|Kirk Cousins       |2015  |145     |9.0625            |379            |23.6875           |543         |33.9375           |4166.0           |260.375           |29             |1.8125             |11.0             |0.6875             |0.6979742173112339   |2.6363636363636362|
|Geno Smith         |2022  |160     |9.411764705882353 |399            |23.470588235294116|572         |33.64705882352941 |4282.0           |251.88235294117646|30             |1.7647058823529411 |11.0             |0.6470588235294118 |0.6975524475524476   |2.727272727272727 |
|Chase Daniel       |2018  |38      |9.5               |53             |13.25             |76          |19.0              |515.0            |128.75            |3              |0.75               |2.0              |0.5                |0.6973684210526315   |1.5               |
|Carson Wentz       |2018  |93      |8.454545454545455 |279            |25.363636363636363|401         |36.45454545454545 |3074.0           |279.45454545454544|21             |1.9090909090909092 |7.0              |0.6363636363636364 |0.6957605985037406   |3.0               |
|Dak Prescott       |2023  |164     |9.647058823529411 |410            |24.11764705882353 |590         |34.705882352941174|4516.0           |265.6470588235294 |36             |2.1176470588235294 |9.0              |0.5294117647058824 |0.6949152542372882   |4.0               |
|Philip Rivers      |2013  |145     |9.0625            |378            |23.625            |544         |34.0              |4478.0           |279.875           |32             |2.0                |11.0             |0.6875             |0.6948529411764706   |2.909090909090909 |
|Tony Romo          |2010  |24      |4.0               |148            |24.666666666666668|213         |35.5              |1605.0           |267.5             |11             |1.8333333333333333 |7.0              |1.1666666666666667 |0.6948356807511737   |1.5714285714285714|
|Kirk Cousins       |2023  |36      |4.5               |216            |27.0              |311         |38.875            |2331.0           |291.375           |18             |2.25               |5.0              |0.625              |0.6945337620578779   |3.6               |
|Matt Ryan          |2018  |145     |9.0625            |422            |26.375            |608         |38.0              |4924.0           |307.75            |35             |2.1875             |7.0              |0.4375             |0.694078947368421    |5.0               |
|Brock Purdy        |2023  |144     |9.0               |308            |19.25             |444         |27.75             |4280.0           |267.5             |31             |1.9375             |11.0             |0.6875             |0.6936936936936937   |2.8181818181818183|
|Jim Sorgi          |2005  |57      |11.4              |43             |8.6               |62          |12.4              |444.0            |88.8              |3              |0.6                |1.0              |0.2                |0.6935483870967742   |3.0               |
|Brandon Weeden     |2015  |45      |7.5               |97             |16.166666666666668|140         |23.333333333333332|1043.0           |173.83333333333334|5              |0.8333333333333334 |2.0              |0.3333333333333333 |0.6928571428571428   |2.5               |
+-------------------+------+--------+------------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+-------------------+-----------------+-------------------+---------------------+------------------+
only showing top 40 rows

In [22]:
# Top 40 by TD to INT ratio
qb_summary_spark_50.orderBy(F.col("td_int_ratio").desc()).show(40, truncate=False)

+-------------------+------+--------+------------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+
|player_display_name|season|week_sum|week_mean         |completions_sum|completions_mean  |attempts_sum|attempts_mean     |passing_yards_sum|passing_yards_mean|passing_tds_sum|passing_tds_mean  |interceptions_sum|interceptions_mean |completion_percentage|td_int_ratio     |
+-------------------+------+--------+------------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+
|Tom Brady          |2016  |134     |11.166666666666666|291            |24.25             |432         |36.0              |3554.0           |296.1666666666667 |28             |2.3333333333333335|2.0              |0.16666666666666666|0.6736111111111112   |14.0             |
|Nick Foles         |2013  |129     |9.923076923076923 |203            |15.615384615384615|317         |24.384615384615383|2891.0           |222.3846153846154 |27             |2.076923076923077 |2.0              |0.15384615384615385|0.6403785488958991   |13.5             |
|Josh McCown        |2013  |92      |11.5              |149            |18.625            |224         |28.0              |1829.0           |228.625           |13             |1.625             |1.0              |0.125              |0.6651785714285714   |13.0             |
|Aaron Rodgers      |2018  |146     |9.125             |372            |23.25             |597         |37.3125           |4442.0           |277.625           |25             |1.5625            |2.0              |0.125              |0.6231155778894473   |12.5             |
|Damon Huard        |2006  |69      |6.9               |148            |14.8              |244         |24.4              |1878.0           |187.8             |11             |1.1               |1.0              |0.1                |0.6065573770491803   |11.0             |
|Aaron Rodgers      |2020  |148     |9.25              |372            |23.25             |526         |32.875            |4299.0           |268.6875          |48             |3.0               |5.0              |0.3125             |0.7072243346007605   |9.6              |
|Aaron Rodgers      |2021  |149     |9.3125            |366            |22.875            |531         |33.1875           |4115.0           |257.1875          |37             |2.3125            |4.0              |0.25               |0.6892655367231638   |9.25             |
|Tom Brady          |2010  |148     |9.25              |324            |20.25             |492         |30.75             |3900.0           |243.75            |36             |2.25              |4.0              |0.25               |0.6585365853658537   |9.0              |
|Jake Delhomme      |2007  |6       |2.0               |55             |18.333333333333332|86          |28.666666666666668|617.0            |205.66666666666666|8              |2.6666666666666665|1.0              |0.3333333333333333 |0.6395348837209303   |8.0              |
|Aaron Rodgers      |2014  |144     |9.0               |341            |21.3125           |520         |32.5              |4381.0           |273.8125          |38             |2.375             |5.0              |0.3125             |0.6557692307692308   |7.6              |
|Aaron Rodgers      |2011  |128     |8.533333333333333 |342            |22.8              |501         |33.4              |4636.0           |309.06666666666666|45             |3.0               |6.0              |0.4                |0.6826347305389222   |7.5              |
|Drew Brees         |2019  |119     |10.818181818181818|281            |25.545454545454547|378         |34.36363636363637 |2979.0           |270.8181818181818 |27             |2.4545454545454546|4.0              |0.36363636363636365|0.7433862433862434   |6.75             |
|Aaron Rodgers      |2019  |142     |8.875             |353            |22.0625           |569         |35.5625           |4002.0           |250.125           |26             |1.625             |4.0              |0.25               |0.6203866432337434   |6.5              |
|Drew Brees         |2018  |130     |8.666666666666666 |364            |24.266666666666666|489         |32.6              |3992.0           |266.1333333333333 |32             |2.1333333333333333|5.0              |0.3333333333333333 |0.7443762781186094   |6.4              |
|Patrick Mahomes    |2020  |126     |8.4               |390            |26.0              |588         |39.2              |4740.0           |316.0             |38             |2.533333333333333 |6.0              |0.4                |0.6632653061224489   |6.333333333333333|
|Tom Brady          |2007  |143     |8.9375            |398            |24.875            |578         |36.125            |4806.0           |300.375           |50             |3.125             |8.0              |0.5                |0.6885813148788927   |6.25             |
|Russell Wilson     |2019  |142     |8.875             |341            |21.3125           |516         |32.25             |4110.0           |256.875           |31             |1.9375            |5.0              |0.3125             |0.6608527131782945   |6.2              |
|David Garrard      |2007  |105     |8.75              |208            |17.333333333333332|325         |27.083333333333332|2509.0           |209.08333333333334|18             |1.5               |3.0              |0.25               |0.64                 |6.0              |
|Matthew Stafford   |2010  |26      |6.5               |57             |14.25             |96          |24.0              |535.0            |133.75            |6              |1.5               |1.0              |0.25               |0.59375              |6.0              |
|Lamar Jackson      |2019  |128     |8.533333333333333 |265            |17.666666666666668|401         |26.733333333333334|3127.0           |208.46666666666667|36             |2.4               |6.0              |0.4                |0.6608478802992519   |6.0              |
|Dak Prescott       |2016  |146     |9.125             |311            |19.4375           |459         |28.6875           |3667.0           |229.1875          |23             |1.4375            |4.0              |0.25               |0.6775599128540305   |5.75             |
|Aaron Rodgers      |2016  |149     |9.3125            |401            |25.0625           |610         |38.125            |4428.0           |276.75            |40             |2.5               |7.0              |0.4375             |0.6573770491803279   |5.714285714285714|
|Peyton Manning     |2013  |144     |9.0               |450            |28.125            |659         |41.1875           |5477.0           |342.3125          |55             |3.4375            |10.0             |0.625              |0.6828528072837633   |5.5              |
|Matt Ryan          |2016  |142     |8.875             |373            |23.3125           |534         |33.375            |4944.0           |309.0             |38             |2.375             |7.0              |0.4375             |0.6985018726591761   |5.428571428571429|
|Patrick Mahomes    |2019  |124     |8.857142857142858 |319            |22.785714285714285|484         |34.57142857142857 |4031.0           |287.92857142857144|26             |1.8571428571428572|5.0              |0.35714285714285715|0.6590909090909091   |5.2              |
|Alex Smith         |2017  |126     |8.4               |341            |22.733333333333334|505         |33.666666666666664|4042.0           |269.46666666666664|26             |1.7333333333333334|5.0              |0.3333333333333333 |0.6752475247524753   |5.2              |
|Tom Brady          |2015  |149     |9.3125            |402            |25.125            |624         |39.0              |4770.0           |298.125           |36             |2.25              |7.0              |0.4375             |0.6442307692307693   |5.142857142857143|
|Jeff Garcia        |2006  |102     |12.75             |116            |14.5              |188         |23.5              |1309.0           |163.625           |10             |1.25              |2.0              |0.25               |0.6170212765957447   |5.0              |
|Matt Ryan          |2018  |145     |9.0625            |422            |26.375            |608         |38.0              |4924.0           |307.75            |35             |2.1875            |7.0              |0.4375             |0.694078947368421    |5.0              |
|Russell Wilson     |2018  |146     |9.125             |280            |17.5              |427         |26.6875           |3448.0           |215.5             |35             |2.1875            |7.0              |0.4375             |0.6557377049180327   |5.0              |
|Geno Smith         |2021  |26      |6.5               |65             |16.25             |95          |23.75             |702.0            |175.5             |5              |1.25              |1.0              |0.25               |0.6842105263157895   |5.0              |
|Aaron Rodgers      |2012  |143     |8.9375            |371            |23.1875           |552         |34.5              |4295.0           |268.4375          |39             |2.4375            |8.0              |0.5                |0.6721014492753623   |4.875            |
|Ryan Tannehill     |2020  |149     |9.3125            |315            |19.6875           |481         |30.0625           |3819.0           |238.6875          |34             |2.125             |7.0              |0.4375             |0.6548856548856549   |4.857142857142857|
|Brett Favre        |2009  |144     |9.0               |364            |22.75             |532         |33.25             |4202.0           |262.625           |33             |2.0625            |7.0              |0.4375             |0.6842105263157895   |4.714285714285714|
|Kirk Cousins       |2021  |147     |9.1875            |372            |23.25             |561         |35.0625           |4221.0           |263.8125          |33             |2.0625            |7.0              |0.4375             |0.6631016042780749   |4.714285714285714|
|Carson Wentz       |2017  |95      |7.3076923076923075|265            |20.384615384615383|440         |33.84615384615385 |3296.0           |253.53846153846155|33             |2.5384615384615383|7.0              |0.5384615384615384 |0.6022727272727273   |4.714285714285714|
|Deshaun Watson     |2020  |145     |9.0625            |382            |23.875            |544         |34.0              |4823.0           |301.4375          |33             |2.0625            |7.0              |0.4375             |0.7022058823529411   |4.714285714285714|
|Derek Carr         |2016  |126     |8.4               |357            |23.8              |560         |37.333333333333336|3937.0           |262.46666666666664|28             |1.8666666666666667|6.0              |0.4                |0.6375               |4.666666666666667|
|Jameis Winston     |2021  |30      |4.285714285714286 |95             |13.571428571428571|161         |23.0              |1170.0           |167.14285714285714|14             |2.0               |3.0              |0.42857142857142855|0.5900621118012422   |4.666666666666667|
|C.J. Stroud        |2023  |133     |8.866666666666667 |319            |21.266666666666666|499         |33.266666666666666|4108.0           |273.8666666666667 |23             |1.5333333333333334|5.0              |0.3333333333333333 |0.6392785571142284   |4.6              |
+-------------------+------+--------+------------------+---------------+------------------+------------+------------------+-----------------+------------------+---------------+------------------+-----------------+-------------------+---------------------+-----------------+
only showing top 40 rows

**Comparison**

The completion percentage results should be very similar across the two APIs.

The touchdown-to-interception ratio can behave differently when `interceptions_sum` is 0:
- pandas-on-Spark may show `inf`
- Spark SQL may show `NULL`